// Global Taxi SPB
// Постоянные значения проекта

const ORDER_STATUS = {
  NEW: "NEW",
  CONFIRMED: "CONFIRMED",
  DRIVER_ASSIGNED: "DRIVER_ASSIGNED",
  DRIVER_ON_WAY: "DRIVER_ON_WAY",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED"
};

const USER_ROLE = {
  CLIENT: "CLIENT",
  DISPATCHER: "DISPATCHER",
  DRIVER: "DRIVER"
};

module.exports = {
  ORDER_STATUS,
  USER_ROLE
};
